"""add_scan_snapshot

Revision ID: 1ac8ad4cd49b
Revises: 7a7aba2b9528
Create Date: 2026-03-24 23:05:38.130592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac8ad4cd49b'
down_revision: Union[str, Sequence[str], None] = '7a7aba2b9528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_symbols', sa.Integer(), nullable=False),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('picks_count', sa.Integer(), nullable=False),
    sa.Column('max_sq_count', sa.Integer(), nullable=False),
    sa.Column('buy_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_snapshot_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('market_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('bb_pct_b', sa.Float(), nullable=True),
    sa.Column('bb_width', sa.Float(), nullable=True),
    sa.Column('squeeze_level', sa.Integer(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=10), nullable=True),
    sa.Column('last_signal', sa.String(length=20), nullable=True),
    sa.Column('last_signal_date', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['scan_snapshot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_item_filter', 'scan_snapshot_item', ['snapshot_id', 'market_type', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshot_item_filter', table_name='scan_snapshot_item')
    op.drop_table('scan_snapshot_item')
    op.drop_table('scan_snapshot')
    # ### end Alembic commands ###
