"""add_trade_record

Revision ID: 1c6afc66268c
Revises: 2e6619788423
Create Date: 2026-03-18 17:14:23.443980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6afc66268c'
down_revision: Union[str, Sequence[str], None] = '2e6619788423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('start_signal', sa.String(length=10), nullable=False),
    sa.Column('start_price', sa.Float(), nullable=False),
    sa.Column('start_date', sa.String(length=30), nullable=False),
    sa.Column('sell_signal_date', sa.String(length=30), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('sell_date', sa.String(length=30), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_record_status', 'trade_record', ['watchlist_id', 'status'], unique=False)
    op.create_table('trade_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_record_id', sa.Integer(), nullable=False),
    sa.Column('entry_no', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.String(length=30), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_record_id'], ['trade_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_entry')
    op.drop_index('idx_trade_record_status', table_name='trade_record')
    op.drop_table('trade_record')
    # ### end Alembic commands ###
