"""add daily_top_pick

Revision ID: 2e6619788423
Revises: 761d49d4c43e
Create Date: 2026-03-16 09:18:03.757472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6619788423'
down_revision: Union[str, Sequence[str], None] = '761d49d4c43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_top_pick',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_date', sa.String(length=10), nullable=False),
    sa.Column('market_type', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('signal_state', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('bb_pct_b', sa.Float(), nullable=True),
    sa.Column('squeeze_level', sa.Integer(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_top_pick_date', 'daily_top_pick', ['scan_date', 'market_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_daily_top_pick_date', table_name='daily_top_pick')
    op.drop_table('daily_top_pick')
    # ### end Alembic commands ###
