"""add_stock_master

Revision ID: 37b24d3153b6
Revises: 818ee1012c69
Create Date: 2026-03-19 21:16:17.144430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b24d3153b6'
down_revision: Union[str, Sequence[str], None] = '818ee1012c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('market_type', sa.String(length=10), nullable=False),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'symbol', name='uq_stock_master')
    )
    op.create_index('idx_stock_master_search', 'stock_master', ['market', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_master_search', table_name='stock_master')
    op.drop_table('stock_master')
    # ### end Alembic commands ###
