"""drop_trade_tables

Revision ID: 818ee1012c69
Revises: 1c6afc66268c
Create Date: 2026-03-19 21:01:00.788192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818ee1012c69'
down_revision: Union[str, Sequence[str], None] = '1c6afc66268c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # trade_entry has FK to trade_record, must drop child first
    op.drop_table('trade_entry')
    op.drop_index(op.f('idx_trade_record_status'), table_name='trade_record')
    op.drop_table('trade_record')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trade_record_id', sa.INTEGER(), nullable=False),
    sa.Column('entry_no', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('entry_date', sa.VARCHAR(length=30), nullable=False),
    sa.Column('memo', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['trade_record_id'], ['trade_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('watchlist_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('start_signal', sa.VARCHAR(length=10), nullable=False),
    sa.Column('start_price', sa.FLOAT(), nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=30), nullable=False),
    sa.Column('sell_signal_date', sa.VARCHAR(length=30), nullable=True),
    sa.Column('sell_price', sa.FLOAT(), nullable=True),
    sa.Column('sell_date', sa.VARCHAR(length=30), nullable=True),
    sa.Column('memo', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_trade_record_status'), 'trade_record', ['watchlist_id', 'status'], unique=False)
    # ### end Alembic commands ###
